# Generated by Django 5.2.9 on 2025-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
