# Generated by Django 5.2.9 on 2025-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image_url_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[('Faol', 'active'), ('Faol emas', 'not active')], default='Not Active'),
        ),
    ]
