# Generated by Django 5.2.9 on 2025-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.CharField(choices=[('active', 'Faol'), ('not_active', 'Faol emas')], default='not_active', max_length=50),
        ),
    ]
