# Generated by Django 5.2.9 on 2025-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('is_paid', "To'landi"), ('is_not_paid', "To'lanmadi")], default='is_not_paid', max_length=20),
        ),
    ]
