# Generated by Django 5.2.9 on 2026-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('payment_waiting', 'Kutilmoqda'), ('is_paid', "To'landi"), ('is_not_paid', "To'lanmadi"), ('canceled', 'Bekor qilindi')], default='is_not_paid', max_length=20),
        ),
    ]
