# Generated by Django 5.2.9 on 2026-01-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='resolution',
            field=models.CharField(choices=[('1080p', '1080p'), ('4k', '4K')], default='1080p', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='group_url_1080p',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='group_url_4k',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1080p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_4k',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
