# Generated by Django 5.2.9 on 2026-02-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_created_at_alter_user_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'bot_starts',
            },
        ),
    ]
