# Generated by Django 5.2.9 on 2026-02-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_botstartuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botstartuser',
            old_name='created_at',
            new_name='started_at',
        ),
    ]
